### ISSUE TITLE
.base-bg-color missing?

### ISSUE THREAD

**Issue by stevage** [antoniandre/wave-ui#141]
Not sure if I'm just doing something wrong or misunderstanding, but the docs say there should be a class `.base-bg-color` and it didn't seem to be there for me.

It should be defined something like:

```
.base-bg-color {
  background:rgb(var(--w-base-bg-color-rgb));
}

```

**Comment by antoniandre** [comment]
Hi @stevage,

You're right, and that's a documentation mistake. Here are the classes you can use as they are defined:

```scss
  .base-color {color: rgba(var(--w-base-color-rgb), 0.7);}
  .base-color--bg {background-color: rgb(var(--w-base-bg-color-rgb));}
  .contrast-color {color: rgba(var(--w-contrast-color-rgb), 0.7);}
  .contrast-color--bg {background-color: rgb(var(--w-contrast-bg-color-rgb));}
```

I will update the documentation now, thanks for reporting!
